### ISSUE TITLE
v0.0.1 checklist

### ISSUE THREAD

**Issue by ctrltz** [ctrltz/meegsim#41]
- [x] check pyproject.toml (authors, version, license, documentation, keywords/classifiers, include/exclude)
- [x] check CHANGELOG (in GitHub and docs)
- [x] check README (add link to the documentation)
- [x] change license to BSD 3-clause similar to other scientific Python packages
- [x] set up pre-commit ruff hook and GitHub action for style check (#52)
- [ ] upload to PyPI :)
